### ISSUE TITLE
[epic] move in-memory datastructures to the database

### ISSUE THREAD

**Issue by 2opremio** [stellar/soroban-rpc#115]
### What problem does your feature solve?

Reduces memory consumption so that we can extend the default history retention to one week (currently at 2 hours for transactions and 24 hours for events). See [the analysis document](https://docs.google.com/document/d/1NSrOuogVTHKTk1QLuMS-d4u-aT20ZeAzIJqiqPn0RHg/edit#heading=h.1my3tarepa0c) for details.

### What would you like to see?

I would like to see the in-memory data-structures (Currently based around `LedgerBucketWindow`) stored in the database instead of in-memory.

Regarding the DB schema, we can either roughly mirror what's kept in memory or use some sort of indexing on the txmeta which is already kept in the DB.

We should also have [the bigger picture](https://docs.google.com/document/d/1tTuzL7HBHedp9TE-LonD1QV67SaBSReQ8YFj9xQIgtA/edit#heading=h.iacejigpgv59) in mind when modifying the schema. The chosen schema should consider extensibility to implement the new Soroban RPC endoints.

I suggest presenting a schema design which should be peer reviewed before jumping to the implementation.

As an output of this ticket we should also get a performance comparison (e.g. through a purposely built Golang benchmark)

### What alternatives are there?

The performance shouldn't considerably degrade. If it does, we should consider caching recent data (particularly for transactions). However, a hybrid in-memory/db approach increases complexity.

## Subtasks

```[tasklist]
### Design
- [x] Design doc for Transactions: https://github.com/stellar/soroban-rpc/issues/130
- [x] Design doc for Events: https://github.com/stellar/soroban-rpc/issues/131
```

```[tasklist]
### Implementation (Transactions)
- [x] Add support for reading transactions with an offset (https://github.com/stellar/go/pull/5274)
- [ ] https://github.com/stellar/soroban-rpc/issues/153
- [ ] https://github.com/stellar/soroban-rpc/issues/140
- [ ] https://github.com/stellar/soroban-rpc/issues/154
- [ ] https://github.com/stellar/soroban-rpc/issues/155
- [ ] https://github.com/stellar/soroban-rpc/issues/110
```

```[tasklist]
### Implementation \[Events]
- [ ] https://github.com/stellar/soroban-rpc/issues/189
- [ ] https://github.com/stellar/soroban-rpc/issues/190
- [ ] https://github.com/stellar/soroban-rpc/issues/191
- [ ] https://github.com/stellar/soroban-rpc/issues/257
```

**Comment by 2opremio** [comment]
Related: https://github.com/stellar/soroban-rpc/issues/60

**Comment by 2opremio** [comment]
@psheth9 can we close this?

Did you do performance tests in AWS?

**Comment by psheth9** [comment]
Yes I am closing this !!

Also performance and sanity checks are being done in this [issue](https://github.com/stellar/soroban-rpc/issues/281)
