### ISSUE TITLE
[epic] Soroban RPC Productionalization

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-rpc#36]
### What ?

This epic covers the soroban-rpc productionalization efforts, grouped by areas.

## Deployment Reliability
- [x] [P1] Startup Health Check (https://github.com/stellar/soroban-tools/pull/449)
    - [x] Note: Make sure the http getHealth returns non-200 status code when failing.
- [ ]  Optional Watchdog
    - [ ]  [P3] (nice-to-have?) https://github.com/stellar/soroban-rpc/issues/30
    - [x]  [P1] Get helm chart using healthcheck to alert/restart soroban-rpc (https://github.com/stellar/soroban-tools/issues/514)
- [x] [P2] https://github.com/stellar/soroban-tools/issues/500
- [x] [P1] https://github.com/stellar/soroban-tools/issues/499

## Monitoring
- [x] [P1] https://github.com/stellar/soroban-tools/issues/496
- [ ] [P3] https://github.com/stellar/soroban-rpc/issues/35
- [x] [P3] https://github.com/stellar/soroban-tools/issues/498
- [x] [P1] https://github.com/stellar/soroban-tools/issues/669

## Logging
- [x] [P1] https://github.com/stellar/soroban-tools/issues/497
    - [x] Log clearly startup conditions
    - [x] Define clear guidelines for each log severity and apply these.
    - [x] Log all requests and their resolution.
- [x] [P2] Cycle through log files
    - [x] Stdout/stderr are automatically handled by systemd for debian install
    - [x] Make sure logs are handled in the helm chart (https://github.com/stellar/soroban-tools/issues/514)
- [ ] [P3] https://github.com/stellar/soroban-rpc/issues/34

## Tracing/Telemetry
- [ ] [P3] https://github.com/stellar/soroban-rpc/issues/33

## Scalability
- [x] [P2] Baseline Performance Testing (https://github.com/stellar/soroban-tools/issues/505)
- [x] [P2] Baseline Memory Profile (https://github.com/stellar/soroban-tools/issues/505)
- [x] [P1] https://github.com/stellar/soroban-tools/issues/554
- [ ] [P1] Limit concurrency on high-cpu handler calls, based on number of available CPUs.
    - [x] https://github.com/stellar/soroban-tools/pull/489
    - [ ] Others TBD based on outcome of performance testing
- [x] [P2] https://github.com/stellar/soroban-tools/issues/506

## Private Instance
- [ ] Add access control so that an operator can have a private application use
    - Planned initial infra providers have said they would rather do this themselves.

## Documentation
- [x] [P2] https://github.com/stellar/soroban-tools/issues/512
- [ ] [P3] https://github.com/stellar/soroban-rpc/issues/32

## Deployment
- [x] [P1] https://github.com/stellar/soroban-tools/issues/507
- [x] Docker image + helm chart
    - [x] [P1] https://github.com/stellar/soroban-tools/issues/382
    - [x] [P1] https://github.com/stellar/soroban-tools/issues/514
- [x] [P1] https://github.com/stellar/packages/pull/183

## Misc
- [x] [P2] https://github.com/stellar/soroban-tools/issues/509
- [ ] [P2] https://github.com/stellar/soroban-rpc/issues/31
- [x] [P1] https://github.com/stellar/soroban-tools/issues/511

**Comment by mollykarcher** [comment]
There are a few issues referenced here still not complete, but they are low-priority. Closing out this epic, and we'll reprioritize the remaining issues at a later time

**Comment by mollykarcher** [comment]
Don't mind me, just testing the github close action https://stellarfoundation.slack.com/archives/C02U19A2A/p1707843214915849
