### ISSUE TITLE
Soroban RPC API: Events by Contract ID (EPIC)

### ISSUE THREAD

**Issue by jcx120** [stellar/soroban-rpc#43]
Subscribe/Unsubscribe to push events via Websocket Subscription by ContractID MVP
  
- [x] Event streaming / subscription API interface: 
  - [x] Finalize API design, provide spec, get feedback https://github.com/stellar/go/issues/4676
   - provide future extensibility by other topics
  - [x] Implement RPC endpoint: https://github.com/stellar/go/issues/4554
  - [x] Implement CLI endpoint: https://github.com/stellar/soroban-cli/issues/61
  - [x] JS Client support: https://github.com/stellar/js-soroban-client/issues/2
- [x] Data Backend
  - [x] stellar/go#4681
  - [x] stellar/go#4682
- [x] Provide DApp Example
  - Extend example fundraising Dapp to support events: https://github.com/stellar/soroban-tools/issues/458

For the initial Nov v1 MVP, assume:
- all components and processes (captive core, file store etc) running locally (for now)
- event replay, filtering are nice to have but not MVP (addressed in design, to be supported in v2)

[References](https://stellarorg.atlassian.net/wiki/spaces/PJC/pages/4402151440/soroban-rpc+API+Docs#Websocket-Subscription)
