### ISSUE TITLE
[epic] RPC / CLI repo split fallout

### ISSUE THREAD

**Issue by mollykarcher** [stellar/soroban-rpc#77]
High-level tracking issue to keep track of the work done and left to do related to the repository split.

- [x] e2e/system-test failure on soroban-cli
- [x] https://github.com/stellar/soroban-rpc/issues/81
- [x] completing remaining rpc release process
- [x] updating documentation (public developer docs)
- [ ] https://github.com/stellar/soroban-rpc/issues/82
- [x] https://github.com/stellar/soroban-rpc/issues/83
- [x] https://github.com/stellar/soroban-rpc/issues/84
- [x] https://github.com/stellar/soroban-rpc/pull/80
- [x] https://github.com/stellar/soroban-rpc/issues/85
- [ ] https://github.com/stellar/soroban-rpc/issues/86

**Comment by psheth9** [comment]
Few more things that I could think of 

- golangcli [failures](https://github.com/stellar/soroban-rpc/actions/workflows/golangci-lint.yml)
- rename soroban-rpc crates to soroban-rpc-rust-client

**Comment by leighmcculloch** [comment]
> * rename soroban-rpc crates to soroban-rpc-rust-client

For consistency with other libs we have, I suggest we use the name `rs-soroban-rpc-client`.

**Comment by psheth9** [comment]
Thanks @leighmcculloch !! we are not moving crate to its own repo at least for now

**Comment by mollykarcher** [comment]
Closing this, the 2 remaining tasks are still on the board but have lower priority than this overall initiative
